#server properties
server:
  port: 9090
  
app.secret: shubh 

 #databse properties 
spring:  datasource:    url: jdbc:mysql://localhost:3306/NeoSOFT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shubh
    
#jpa properties  jpa:    show-sql: true
    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  
     